#include <iostream>
#include <random>

/**
 * @brief Generates a random integer in the given range.
 *
 * Utilizes the Mersenne Twister engine seeded with a random device to generate
 * a random integer within the specified range [low, high].
 *
 * @param low Minimum possible value (default: 0).
 * @param high Maximum possible value (default: 10).
 * @return Randomly generated integer.
 */
int randNum(int low = 0, int high = 10) {
    std::random_device rd;  // Seed for randomness
    std::mt19937 gen(rd()); // Mersenne Twister generator
    std::uniform_int_distribution<> dis(low, high);
    return dis(gen);
}

/**
 * @brief Creates a dynamically allocated 1D array and fills it with random values.
 *
 * Allocates memory for a 1D array of integers and fills it with random integers
 * generated by randNum() within the default range [0, 10].
 *
 * @param size Size of the array.
 * @return Pointer to the dynamically allocated 1D array.
 */
int* create1DArray(int size) {
    int* arr = new int[size];
    for (int i = 0; i < size; i++)
        arr[i] = randNum();
    return arr;
}

/**
 * @brief Creates a dynamically allocated 2D array using an array of pointers.
 *
 * Allocates memory for a 2D array where each row is a dynamically allocated 1D array.
 * Each element is filled with random integers using randNum().
 *
 * @param rows Number of rows.
 * @param cols Number of columns.
 * @return Pointer to the dynamically allocated 2D array.
 */
int** create2DArray(int rows, int cols) {
    int** array2d = new int*[rows];
    for (int i = 0; i < rows; i++)
        array2d[i] = create1DArray(cols);
    return array2d;
}

/**
 * @brief Creates a dynamically allocated 3D array using pointers to pointers.
 *
 * Allocates memory for a 3D array, where each depth layer contains a 2D array.
 * Each element is filled with random integers using randNum().
 *
 * @param depth Number of depth layers.
 * @param rows Number of rows per depth.
 * @param cols Number of columns per row.
 * @return Pointer to the dynamically allocated 3D array.
 */
int*** create3DArray(int depth, int rows, int cols) {
    int*** array3d = new int**[depth];
    for (int i = 0; i < depth; i++)
        array3d[i] = create2DArray(rows, cols);
    return array3d;
}

/**
 * @brief Displays a 1D array.
 *
 * Iterates through the given 1D array and prints each element separated by commas.
 *
 * @param arr Pointer to the 1D array.
 * @param size Size of the array.
 */
void display(int* arr, int size) {
    for (int i = 0; i < size; i++)
        std::cout << arr[i] << ", ";
    std::cout << std::endl;
}

/**
 * @brief Deallocates memory for a dynamically allocated 1D array.
 *
 * Frees the memory allocated for a 1D array and prevents dangling pointers by setting it to nullptr.
 *
 * @param arr Pointer to the 1D array.
 */
void deallocate1DArray(const int* arr) {
    if (arr == nullptr) return;
    delete[] arr;
    arr = nullptr;
}

/**
 * @brief Deallocates memory for a dynamically allocated 2D array.
 *
 * Frees memory for each 1D array (row) and then for the array of pointers.
 * Sets the array pointer to nullptr to prevent dangling pointers.
 *
 * @param array Pointer to the 2D array.
 * @param rows Number of rows.
 */
void deallocate2DArray(int** array, const int& rows) {
    if (array == nullptr) return;
    for (int i = 0; i < rows; i++) deallocate1DArray(array[i]);
    delete[] array;
    array = nullptr;
}

/**
 * @brief Deallocates memory for a dynamically allocated 3D array.
 *
 * Frees memory for each 2D array (depth layer), then for each row within the 2D arrays,
 * and finally for the array of depth pointers. Sets the array pointer to nullptr to prevent dangling pointers.
 *
 * @param array Pointer to the 3D array.
 * @param depth Number of depth layers.
 * @param rows Number of rows per depth layer.
 */
void deallocate3DArray(int*** array, const int& depth, const int& rows) {
    if (array == nullptr) return;
    for (int i = 0; i < depth; i++) deallocate2DArray(array[i], rows);
    delete[] array;
    array = nullptr;
}

/**
 * @brief Main function demonstrating dynamic array allocation and deallocation.
 *
 * Creates and displays 1D, 2D, and 3D arrays filled with random integers.
 * Properly deallocates all allocated memory to avoid memory leaks.
 *
 * @return int Exit status.
 */
int main() {
    int* onedarray = create1DArray(5);
    int** twodarray = create2DArray(3, 3);
    int*** threedarray = create3DArray(2, 3, 3);

    std::cout << "---1D---" << std::endl;
    display(onedarray, 5);

    std::cout << "---2D---" << std::endl;
    display(twodarray[0], 3);
    display(twodarray[1], 3);
    display(twodarray[2], 3);

    std::cout << "---3D---" << std::endl;
    display(threedarray[0][0], 3);
    display(threedarray[0][1], 3);
    display(threedarray[0][2], 3);
    std::cout << std::endl;
    display(threedarray[1][0], 3);
    display(threedarray[1][1], 3);
    display(threedarray[1][2], 3);

    // Cleanup
    deallocate1DArray(onedarray);
    deallocate2DArray(twodarray, 3);
    deallocate3DArray(threedarray, 2, 3);

    return 0;
}